apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: NodePort
  ports:
  - port: 9555
    targetPort: 9555
  selector:
    app: adservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: delalixx/adservice:latest
        ports:
        - containerPort: 9555
        env:
        - name: MESSAGE
          value: Hello from my first microservices deployment!
#### END of ADSERVICE ###
#------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: adservice
        image: delalixx/frontend:latest
        ports:
        - containerPort: 5050
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
