pipeline {
  agent {dockerfile true}
    
    stages {
        stage('Clone Repository') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'kubectl apply -f <kubernetes-manifest-file>.yml'
            }
        }
    }
}
